# Generated by Django 4.2.4 on 2023-10-10 02:29

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_loyalty_filing_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementos_alquilar', models.TextField(max_length=1000, verbose_name='Elementos seleccionados')),
                ('precio_total', models.IntegerField(verbose_name='Precio Total')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
            options={
                'verbose_name': 'Carrito Alquiler',
                'verbose_name_plural': 'Carrito de Alquileres',
                'db_table': 'Carrito_alquiler',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.AlterModelOptions(
            name='statepqrsd',
            options={'ordering': ['id'], 'verbose_name': 'Estado pqrsd', 'verbose_name_plural': 'Estados pqrsd'},
        ),
        migrations.AlterModelOptions(
            name='stateproduct',
            options={'ordering': ['id'], 'verbose_name': 'Estado Producto', 'verbose_name_plural': 'Estados productos'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='guest_document',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='type_pay',
        ),
        migrations.RemoveField(
            model_name='statepqrsd',
            name='StatePqrsd',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='idle',
        ),
        migrations.AddField(
            model_name='statepqrsd',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='statepqrsd',
            name='loyalty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loyalty'),
        ),
        migrations.AddField(
            model_name='stateproduct',
            name='estadoP',
            field=models.CharField(choices=[('Activo ', 'Activo '), ('Inactivo ', 'Inactivo ')], default='Activo ', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='filing_number',
            field=models.PositiveIntegerField(default=core.models.generate_random_radicado, verbose_name='Guarde el Número de radicado para consultar el estado de su PQRSD'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='preference_contact',
            field=models.ForeignKey(help_text='&nbsp', on_delete=django.db.models.deletion.CASCADE, to='core.preferencecontact', verbose_name='Como prefiere ser contactad@'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='type_pqrsd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typepqrsd', verbose_name='Tipo de PQRSD'),
        ),
        migrations.AlterField(
            model_name='pse',
            name='select_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.selectbank', verbose_name='Seleccione su Banco'),
        ),
        migrations.AlterField(
            model_name='pse',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeid', verbose_name='Tipo de Identificación'),
        ),
        migrations.AlterField(
            model_name='pse',
            name='type_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeperson', verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='campus',
            field=models.CharField(max_length=200, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='description',
            field=models.CharField(help_text='Descipcion del evento Mas detallado ', max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='eventType',
            field=models.CharField(max_length=200, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='lounge',
            field=models.CharField(max_length=200, verbose_name='Salón'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='theme',
            field=models.CharField(choices=[('Campestre', 'Campestre'), ('Neon', 'Neon'), ('Alfombra_Roja', 'Alfombra Roja'), ('Personaje_Disney', 'Personaje Disney'), ('Flores', 'Flores'), ('Noche_estrellas', 'Noche de Estrellas'), ('Tropical', 'Tropical'), ('Mariposas', 'Mariposas')], default='Mari´posas', max_length=200, verbose_name='Tematica'),
        ),
        migrations.AlterField(
            model_name='stateproduct',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AlterField(
            model_name='tarjetadecd',
            name='expiration',
            field=models.CharField(max_length=5, verbose_name='Vencimiento'),
        ),
        migrations.AlterModelTable(
            name='statepqrsd',
            table='estado_pqrsd',
        ),
        migrations.AlterModelTable(
            name='stateproduct',
            table='estado_producto',
        ),
    ]
